db:
  host: "34.22.69.235"
  port: "5432"
  username: "dev"
  password: "glab0110!!"
  database: "ai-resume"
  pool_size: 2
  max_overflow: 3
  pool_timeout: 10
  pool_recycle: 300

cors_origins:
  - "*"

